### ISSUE TITLE
which branch to you use here?

### ISSUE THREAD

**Issue by RandyMcMillan** [joshka/ratatui-json-tutorial#1]
https://github.com/joshka/ratatui-json-tutorial/blob/2c1986ff26e65de76ebfad1d48ffd11d2b1e6a9b/Cargo.toml#L19

**Comment by joshka** [comment]
Just the latest version of Ratatui should be enough.

It was likely that I was using a version of Ratatui that I had locally and using some random bug fix. I don't recall what that would have been (correlate commit times in Ratatui to here if you're interested). Instead just updated the app code to be a bit more Ratatui 0.28.1 focused in https://github.com/joshka/ratatui-json-tutorial/pull/2.
